### ISSUE TITLE
 Initializing Firebase Messaging failed

### ISSUE THREAD

**Issue by MohammadBarati** [push-pole/android-studio-sample#3]
`PushPole: Sending upstream message failed
    com.pushpole.sdk.a: Initializing Firebase Messaging failed`

**Comment by conall1995** [comment]
try to use pushsdk:1.7.1 
change lib ver like this 
    `implementation 'com.pushpole.android:pushsdk:1.7.1'`
   ` implementation 'com.google.firebase:firebase-messaging:20.1.0'`
   `implementation 'com.google.firebase:firebase-iid:20.0.2'`
